import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { PLATFORM_PRICES, type PlanType, type BillingInterval } from "@/lib/entitlements";
import { createPaystackPlan, paystackRequest } from "@/lib/paystack";
const LABELS:any={FAN:"All-access fan pass",CREATOR:"Creator plan"};
async function ensurePlan(planType:PlanType,interval:BillingInterval){const key=`platform_${planType}_${interval}`;const existing=await prisma.paystackPlan.findUnique({where:{key}});if(existing)return existing;const plan=await createPaystackPlan({name:`${LABELS[planType]} ${interval}`,amount:PLATFORM_PRICES[planType][interval],interval:interval==="MONTHLY"?"monthly":"annually",currency:"NGN",description:`${LABELS[planType]} subscription`});return prisma.paystackPlan.create({data:{key,name:plan.name,planCode:plan.plan_code,amount:PLATFORM_PRICES[planType][interval],currency:"NGN",interval:interval==="MONTHLY"?"monthly":"annually"}});}
export async function POST(req:Request){const session=await getServerSession(authOptions);if(!session?.user)return NextResponse.json({error:"Not authenticated"},{status:401});const userId=(session.user as any).id as string;const {planType,billingInterval}=await req.json().catch(()=>({}));if(!["FAN","CREATOR"].includes(planType)||!["MONTHLY","YEARLY"].includes(billingInterval))return NextResponse.json({error:"Invalid subscription plan"},{status:400});const user=await prisma.user.findUnique({where:{id:userId},select:{isAmbassador:true,email:true}});if(user?.isAmbassador){await prisma.platformSubscription.upsert({where:{paystackSubscriptionCode:`ambassador-${userId}-${planType}`},create:{userId,planType,billingInterval,status:"active",paystackSubscriptionCode:`ambassador-${userId}-${planType}`,currentPeriodEnd:new Date("2100-01-01")},update:{status:"active",currentPeriodEnd:new Date("2100-01-01")}});return NextResponse.json({free:true});}try{const plan=await ensurePlan(planType as PlanType,billingInterval as BillingInterval);const existing=await prisma.platformSubscription.findFirst({where:{userId,planType}});const row=existing?await prisma.platformSubscription.update({where:{id:existing.id},data:{status:"pending",billingInterval,paystackPlanCode:plan.planCode}}):await prisma.platformSubscription.create({data:{userId,planType,billingInterval,status:"pending",paystackPlanCode:plan.planCode,currentPeriodEnd:new Date(0)}});const origin=process.env.NEXTAUTH_URL??new URL(req.url).origin;const ref=`platform_${row.id}_${Date.now()}`;const data=await paystackRequest('/transaction/initialize',{method:'POST',body:JSON.stringify({email:user?.email,amount:String(plan.amount),currency:'NGN',plan:plan.planCode,reference:ref,callback_url:`${origin}/api/paystack/callback`,metadata:{type:'PLATFORM_SUBSCRIPTION',platformSubscriptionId:row.id,userId,planType,billingInterval}})});return NextResponse.json({url:data.data.authorization_url});}catch(e){console.error(e);return NextResponse.json({error:e instanceof Error?e.message:"Unable to start Paystack subscription"},{status:502});}}
