"use client";
import { useEffect,useState } from "react";
type Dare={id:string;tier:string;tokenAmount:number;prompt?:string;isActive?:boolean};
export default function DarePanel({roomName,isCreator}:{roomName:string;isCreator:boolean}){const [dares,setDares]=useState<Dare[]>([]);const [tier,setTier]=useState('SIMPLE');const [prompt,setPrompt]=useState('');const [amount,setAmount]=useState('100');const [busy,setBusy]=useState(false);const [reveals,setReveals]=useState<any[]>([]);const [revealBusy,setRevealBusy]=useState(false);
async function load(){const r=await fetch(`/api/live/dares?roomName=${encodeURIComponent(roomName)}`);const d=await r.json();if(r.ok)setDares(d.dares||[]);const rr=await fetch(`/api/live/dare/reveals?roomName=${encodeURIComponent(roomName)}`);const rd=await rr.json();if(rr.ok)setReveals(rd.reveals||[])}
useEffect(()=>{load();const t=setInterval(load,4000);return()=>clearInterval(t)},[roomName]);
async function add(){setBusy(true);const r=await fetch('/api/live/dares',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomName,tier,prompt,tokenAmount:Number(amount)})});const d=await r.json();setBusy(false);if(r.ok){setDares(x=>[d.dare,...x]);setPrompt('')}else alert(d.error||'Could not add dare')}
async function buy(requestedTier:string){setTier(requestedTier);setRevealBusy(true);const r=await fetch('/api/live/dare/purchase',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomName,tier:requestedTier})});const d=await r.json();setRevealBusy(false);if(r.ok){setReveals(x=>[d.reveal,...x])}else if(r.status===402){if(confirm(d.error+' Go to token packs?'))window.location.href='/tokens'}else alert(d.error||'Could not purchase dare')}
return <section className="mt-4 rounded-2xl bg-stone-900 p-4">{isCreator?<><h2 className="font-semibold">🎯 Your hidden Dare bank</h2><p className="mt-1 text-xs text-stone-400">Fans only see the section and token price until they pay; the selected dare is then revealed to both sides.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><select value={tier} onChange={e=>setTier(e.target.value)} className="rounded-lg bg-white px-3 py-2 text-sm text-stone-900"><option value="SIMPLE">Simple</option><option value="BASIC">Basic</option><option value="EXTREME">Extreme</option></select><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="1" className="rounded-lg bg-white px-3 py-2 text-sm text-stone-900" placeholder="FV tokens"/><button onClick={add} disabled={busy||!prompt.trim()} className="rounded-lg bg-[--accent] px-3 py-2 text-sm disabled:opacity-50">Add dare</button></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={500} className="mt-2 w-full rounded-lg bg-white px-3 py-2 text-sm text-stone-900" placeholder="Write a safe, consensual dare…"/><div className="mt-3 space-y-2">{dares.map(d=><div key={d.id} className="rounded-lg bg-stone-800 p-3 text-sm"><b>{d.tier}</b> · ⭐ {d.tokenAmount.toLocaleString()} · {d.prompt}</div>)}</div></>:<><h2 className="font-semibold">🎯 Choose a Dare</h2><p className="mt-1 text-xs text-stone-400">Pay FV Tokens and one hidden dare from that section will be revealed to you and the creator.</p><div className="mt-3 flex flex-wrap gap-2">{['SIMPLE','BASIC','EXTREME'].map(t=><button key={t} onClick={()=>buy(t)} disabled={revealBusy} className="rounded-full bg-[--accent] px-4 py-2 text-sm disabled:opacity-50">{t[0]+t.slice(1).toLowerCase()} dare</button>)}</div></>}{reveals.length>0&&<div className="mt-4 space-y-2"><h3 className="text-sm font-medium">Latest revealed dares</h3>{reveals.map(r=><div key={r.id} className="rounded-xl border border-stone-700 bg-stone-800 p-3 text-sm"><div className="text-xs text-stone-400">{r.tier} · ⭐ {r.tokenAmount.toLocaleString()} {isCreator&&r.fanName?`· ${r.fanName}`:''}</div><p className="mt-1">{r.prompt}</p></div>)}</div>}</section>}
