"use client";
import { useEffect, useState } from "react";
import { LiveKitRoom, VideoConference } from "@livekit/components-react";
import "@livekit/components-styles";
import ReportButton from "./ReportButton";
import DarePanel from "./DarePanel";
import GiftStickerPicker from "./GiftStickerPicker";

type Gift = { id:string; label:string; emoji:string; category:"HOT"|"WISH"|"LUXURY"; tokenAmount:number };

export default function LiveRoom({ roomName, roomId, title, creatorName, category }: { roomName:string; roomId:string; title:string; creatorName:string; category?:"NORMAL"|"MATURE"|"DARE" }) {
  const [token,setToken]=useState<string>(); const [url,setUrl]=useState<string>(); const [isCreator,setIsCreator]=useState(false); const [error,setError]=useState(""); const [gift,setGift]=useState(false); const [tipMenu,setTipMenu]=useState<Gift[]>([]); const [matureConfirmed,setMatureConfirmed]=useState(category!=="MATURE");
  useEffect(()=>{if(category==="MATURE"&&!matureConfirmed)return;setError("");fetch('/api/live/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomName})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setToken(d.token);setUrl(d.url);setIsCreator(d.isCreator)}).catch(e=>setError(e.message));fetch(`/api/live/tip-menu?roomName=${encodeURIComponent(roomName)}`).then(async r=>{const d=await r.json();if(r.ok)setTipMenu(d.items||[])}).catch(()=>{});},[roomName,category,matureConfirmed]);
  async function confirmAdult(){const r=await fetch('/api/account/adult-confirm',{method:'POST'});if(r.ok)setMatureConfirmed(true);}
  async function sendGift(tokenAmount:number){setGift(true);const r=await fetch('/api/live/gift',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomName,tokenAmount})});const d=await r.json();setGift(false);if(!r.ok)alert(d.error||'Could not send gift');}
  async function endLive(){await fetch('/api/live/end',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId})});window.location.href='/live';}
  if(category==="MATURE"&&!matureConfirmed)return <main className="mx-auto max-w-3xl px-6 py-10"><div className="rounded-2xl border border-amber-700/40 bg-stone-950 p-8 text-center text-white"><div className="text-4xl">🔞</div><h1 className="mt-3 text-xl font-semibold">18+ Mature live</h1><p className="mt-2 text-sm text-stone-400">You must be 18 or older to enter this section. This confirmation does not replace any age-verification obligations required by law.</p><button onClick={confirmAdult} className="mt-5 rounded-full bg-[--accent] px-5 py-2.5 text-sm font-medium text-white">I am 18 or older</button><a href="/live" className="ml-2 inline-flex rounded-full border border-stone-700 px-5 py-2.5 text-sm font-medium text-white">Go back</a></div></main>;
  if(error)return <main className="mx-auto max-w-3xl px-6 py-10"><div className="rounded-2xl border border-red-900/40 bg-stone-950 p-8 text-center text-white"><div className="text-4xl">🔒</div><h1 className="mt-3 text-xl font-semibold">Live access unavailable</h1><p className="mt-2 text-sm text-stone-400">{error}</p><a href="/dashboard" className="mt-5 inline-flex rounded-full bg-[--accent] px-5 py-2.5 text-sm font-medium text-white">Dashboard</a></div></main>;
  if(!token||!url)return <main className="mx-auto max-w-3xl px-6 py-10"><p>Connecting to live…</p></main>;
  return <main className="min-h-screen bg-stone-950 px-4 py-6 text-white"><div className="mx-auto max-w-5xl"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-red-400">● LIVE · {category==="MATURE"?"18+ Mature":category==="DARE"?"Dare":"Normal"}</p><h1 className="text-2xl font-semibold">{title}</h1><p className="text-sm text-stone-400">{creatorName}</p><ReportButton targetType="LIVE_ROOM" targetId={roomId} label="Report live" /></div>{isCreator&&<button onClick={endLive} className="rounded-full bg-white px-4 py-2 text-sm font-medium text-stone-900">End live</button>}</div><div className="overflow-hidden rounded-2xl bg-black"><LiveKitRoom token={token} serverUrl={url} connect video={isCreator} audio={isCreator}><VideoConference /></LiveKitRoom></div>{category==="DARE"&&<DarePanel roomName={roomName} isCreator={isCreator}/>} {!isCreator&&<div className="mt-4 rounded-2xl bg-stone-900 p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Send a sticker gift</h2><p className="text-xs text-stone-400">Choose a sticker and send it with FV Tokens.</p><a href="/tokens" className="text-xs text-amber-400 underline">Buy FV Tokens</a></div><GiftStickerPicker gifts={tipMenu} disabled={gift} onSend={sendGift}/></div>{tipMenu.length===0&&<p className="mt-3 text-sm text-stone-500">This creator hasn't added any gifts yet.</p>}</div>}</div></main>;
}
