import crypto from "crypto";
import { NextResponse } from "next/server";
import { verifyPaystackTransaction } from "@/lib/paystack";
import { creditTokenPurchase } from "@/lib/tokenPurchase";
import { prisma } from "@/lib/prisma";
export const runtime="nodejs";
function metadataOf(v:any){return typeof v.metadata==='string'?JSON.parse(v.metadata||"{}"):v.metadata||{}}
async function updateCreator(subId:string,reference:string,verified:any){const sub=await prisma.subscription.findUnique({where:{id:subId}});if(!sub)return;const end=new Date(Date.now()+30*86400000);await prisma.subscription.update({where:{id:sub.id},data:{status:"active",currentPeriodEnd:end,nextChargeAt:end,paystackSubscriptionCode:verified.subscription_code||sub.paystackSubscriptionCode,paystackAuthorizationCode:verified.authorization?.authorization_code||sub.paystackAuthorizationCode,lastPaymentReference:reference,amountKobo:sub.amountKobo||Number(verified.amount)}})}
async function updatePlatform(subId:string,reference:string,verified:any){const sub=await prisma.platformSubscription.findUnique({where:{id:subId}});if(!sub)return;const days=sub.billingInterval==="YEARLY"?365:30;const end=new Date(Date.now()+days*86400000);await prisma.platformSubscription.update({where:{id:sub.id},data:{status:"active",currentPeriodEnd:end,nextChargeAt:end,paystackSubscriptionCode:verified.subscription_code||sub.paystackSubscriptionCode,paystackAuthorizationCode:verified.authorization?.authorization_code||sub.paystackAuthorizationCode,lastPaymentReference:reference}})}
export async function POST(req:Request){const body=await req.text();const signature=req.headers.get("x-paystack-signature");const secret=process.env.PAYSTACK_SECRET_KEY;if(!signature||!secret)return NextResponse.json({error:"Missing signature"},{status:400});const expected=crypto.createHmac("sha512",secret).update(body).digest("hex");if(!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return NextResponse.json({error:"Invalid signature"},{status:400});const event=JSON.parse(body);try{
 if(event.event==="charge.success"&&event.data?.reference){const verified=await verifyPaystackTransaction(event.data.reference);const meta=metadataOf(verified);
   if(meta.type==="CREATOR_SUBSCRIPTION"||meta.type==="CREATOR_SUBSCRIPTION_RENEWAL") await updateCreator(meta.subscriptionId,event.data.reference,verified);
   else if(meta.type==="PLATFORM_SUBSCRIPTION") await updatePlatform(meta.platformSubscriptionId,event.data.reference,verified);
   else if(verified.subscription_code){const c=await prisma.subscription.findUnique({where:{paystackSubscriptionCode:verified.subscription_code}});if(c) await updateCreator(c.id,event.data.reference,verified);else {const p=await prisma.platformSubscription.findUnique({where:{paystackSubscriptionCode:verified.subscription_code}});if(p) await updatePlatform(p.id,event.data.reference,verified);else await creditTokenPurchase(event.data.reference,verified.status,Number(verified.amount),verified.currency)}}
   else await creditTokenPurchase(event.data.reference,verified.status,Number(verified.amount),verified.currency);
 }
 if(event.event==="subscription.create"&&event.data?.subscription_code){const code=event.data.subscription_code;const planCode=event.data.plan?.plan_code||null;const email=event.data.customer?.email||null;if(email&&planCode){const u=await prisma.user.findUnique({where:{email},select:{id:true}});if(u)await prisma.platformSubscription.updateMany({where:{userId:u.id,paystackPlanCode:planCode},data:{paystackSubscriptionCode:code,status:"active"}})}}
 if(event.event==="invoice.payment_failed"&&event.data?.subscription?.subscription_code){await prisma.platformSubscription.updateMany({where:{paystackSubscriptionCode:event.data.subscription.subscription_code},data:{status:"past_due"}})}
 if(event.event==="subscription.disable"&&event.data?.subscription_code){await prisma.subscription.updateMany({where:{paystackSubscriptionCode:event.data.subscription_code},data:{status:"canceled"}});await prisma.platformSubscription.updateMany({where:{paystackSubscriptionCode:event.data.subscription_code},data:{status:"canceled"}})}
 }catch(e){console.error("Paystack webhook processing failed",e);return NextResponse.json({error:"Webhook processing failed"},{status:500})}return NextResponse.json({received:true})}
